VIAL_ENABLE = yes
VIA_ENABLE  = no    # ここは容量が厳しければ no にしてOK（Vialだけにする）

POINTING_DEVICE_ENABLE = yes

TAP_DANCE_ENABLE = yes
EXTRAKEY_ENABLE  = yes  # 使わないなら no

RGBLIGHT_ENABLE = no
OLED_ENABLE     = no

LTO_ENABLE      = yes

CONSOLE_ENABLE  = no
COMMAND_ENABLE  = no
MOUSEKEY_ENABLE = no
QMK_SETTINGS    = no

SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
